name: pkgdown

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install system dependencies
        run: |
          brew install pandoc
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE, type = "binary")
          install.packages("pkgdown")
        shell: Rscript {0}
      - name: Install package
        run: |
          R CMD INSTALL .
      - name: Deploy package
        run: |
          git config --local user.email "info@munterfinger.ch"
          git config --local user.name "Merlin Unterfinger"
          Rscript -e "pkgdown::deploy_to_branch(new_process = FALSE)"
